name: Build and Package

on:
  push:
    paths:
      - 'requiredaction/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'

    - name: Build with Maven
      run: mvn -f requiredaction/pom.xml package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: requiredaction/target/*.jar

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awscli --upgrade --user

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_PUBLIC_BUCKET }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_PUBLIC_BUCKET }}

    - name: Upload JAR to S3
      run: |
        aws s3 cp requiredaction/target/*.jar s3://solal-pub/requiredaction.jar
