name: Build and Package

on:
  push:
    paths:
      - 'requiredaction/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: '20'

    - name: Build with Maven
      run: mvn -f requiredaction/pom.xml package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: requiredaction/target/*.jar
